In [176]:
import pandas as pd
import numpy as np
df = pd.read_csv(r"C:\Users\TylerHa\Documents\GitHub\Python\Data\865214564_T_T100_MARKET_ALL_CARRIER.csv")

df

,PASSENGERS,FREIGHT,MAIL,DISTANCE,UNIQUE_CARRIER,AIRLINE_ID,UNIQUE_CARRIER_NAME,UNIQUE_CARRIER_ENTITY,REGION,CARRIER,...,DEST_STATE_NM,DEST_COUNTRY,DEST_COUNTRY_NAME,DEST_WAC,YEAR,QUARTER,MONTH,DISTANCE_GROUP,CLASS,DATA_SOURCE
0,0.0,53185.0,0.0,8165.0,EK,20392,Emirates,9678A,I,EK,...,Texas,US,United States,74,2019,1,3,17,G,IF
1,0.0,9002.0,0.0,6849.0,EK,20392,Emirates,9678A,I,EK,...,New York,US,United States,22,2019,1,3,14,G,IF
2,0.0,2220750.0,0.0,7247.0,EK,20392,Emirates,9678A,I,EK,...,Illinois,US,United States,41,2019,1,3,15,G,IF
3,0.0,1201490.0,0.0,8165.0,EK,20392,Emirates,9678A,I,EK,...,NaN,AE,United Arab Emirates,678,2019,1,3,17,G,IF
4,0.0,248642.0,0.0,6849.0,EK,20392,Emirates,9678A,I,EK,...,NaN,AE,United Arab Emirates,678,2019,1,3,14,G,IF
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
321404,96984.0,505308.0,15979.0,1448.0,AS,19930,Alaska Airlines Inc.,06031,D,AS,...,Washington,US,United States,93,2019,3,7,3,F,DU
321405,97011.0,473666.0,55963.0,1448.0,AS,19930,Alaska Airlines Inc.,06031,D,AS,...,Alaska,US,United States,1,2019,2,6,3,F,DU
321406,97098.0,592775.0,18834.0,1448.0,AS,19930,Alaska Airlines Inc.,06031,D,AS,...,Washington,US,United States,93,2019,3,8,3,F,DU
321407,97329.0,210292.0,5431.0,404.0,DL,19790,Delta Air Lines Inc.,01260,D,DL,...,Georgia,US,United States,34,2019,1,3,1,F,DU
321408,97644.0,390399.0,44506.0,1448.0,AS,19930,Alaska Airlines Inc.,06031,D,AS,...,Alaska,US,United States,1,2019,3,7,3,F,DU

In [177]:
# 1. Read in the data and convert the column names to lowercase to make them easier to work with.
df.columns = df.columns.str.lower()
df

,passengers,freight,mail,distance,unique_carrier,airline_id,unique_carrier_name,unique_carrier_entity,region,carrier,...,dest_state_nm,dest_country,dest_country_name,dest_wac,year,quarter,month,distance_group,class,data_source
0,0.0,53185.0,0.0,8165.0,EK,20392,Emirates,9678A,I,EK,...,Texas,US,United States,74,2019,1,3,17,G,IF
1,0.0,9002.0,0.0,6849.0,EK,20392,Emirates,9678A,I,EK,...,New York,US,United States,22,2019,1,3,14,G,IF
2,0.0,2220750.0,0.0,7247.0,EK,20392,Emirates,9678A,I,EK,...,Illinois,US,United States,41,2019,1,3,15,G,IF
3,0.0,1201490.0,0.0,8165.0,EK,20392,Emirates,9678A,I,EK,...,NaN,AE,United Arab Emirates,678,2019,1,3,17,G,IF
4,0.0,248642.0,0.0,6849.0,EK,20392,Emirates,9678A,I,EK,...,NaN,AE,United Arab Emirates,678,2019,1,3,14,G,IF
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
321404,96984.0,505308.0,15979.0,1448.0,AS,19930,Alaska Airlines Inc.,06031,D,AS,...,Washington,US,United States,93,2019,3,7,3,F,DU
321405,97011.0,473666.0,55963.0,1448.0,AS,19930,Alaska Airlines Inc.,06031,D,AS,...,Alaska,US,United States,1,2019,2,6,3,F,DU
321406,97098.0,592775.0,18834.0,1448.0,AS,19930,Alaska Airlines Inc.,06031,D,AS,...,Washington,US,United States,93,2019,3,8,3,F,DU
321407,97329.0,210292.0,5431.0,404.0,DL,19790,Delta Air Lines Inc.,01260,D,DL,...,Georgia,US,United States,34,2019,1,3,1,F,DU
321408,97644.0,390399.0,44506.0,1448.0,AS,19930,Alaska Airlines Inc.,06031,D,AS,...,Alaska,US,United States,1,2019,3,7,3,F,DU

In [178]:
# 2. What columns are in the data?
df.columns

Index(['passengers', 'freight', 'mail', 'distance', 'unique_carrier',
       'airline_id', 'unique_carrier_name', 'unique_carrier_entity', 'region',
       'carrier', 'carrier_name', 'carrier_group', 'carrier_group_new',
       'origin_airport_id', 'origin_airport_seq_id', 'origin_city_market_id',
       'origin', 'origin_city_name', 'origin_state_abr', 'origin_state_fips',
       'origin_state_nm', 'origin_country', 'origin_country_name',
       'origin_wac', 'dest_airport_id', 'dest_airport_seq_id',
       'dest_city_market_id', 'dest', 'dest_city_name', 'dest_state_abr',
       'dest_state_fips', 'dest_state_nm', 'dest_country', 'dest_country_name',
       'dest_wac', 'year', 'quarter', 'month', 'distance_group', 'class',
       'data_source'],
      dtype='object')

In [179]:
# 3. How many distinct carrier names are in the dataset?
carrier_count = df['carrier'].nunique()
carrier_count

319

In [180]:
# 4. Calculate the totals of the freight, mail, and passengers columns for flights from the United Kingdom to the United States.
df_cutdown = df[['origin_country','dest_country','passengers','freight','mail']]
df_cutdown

       origin_country dest_country  passengers    freight     mail
0                  AE           US         0.0    53185.0      0.0
1                  AE           US         0.0     9002.0      0.0
2                  AE           US         0.0  2220750.0      0.0
3                  US           AE         0.0  1201490.0      0.0
4                  US           AE         0.0   248642.0      0.0
...               ...          ...         ...        ...      ...
321404             US           US     96984.0   505308.0  15979.0
321405             US           US     97011.0   473666.0  55963.0
321406             US           US     97098.0   592775.0  18834.0
321407             US           US     97329.0   210292.0   5431.0
321408             US           US     97644.0   390399.0  44506.0

[321409 rows x 5 columns]

In [181]:
# 4. Calculate the totals of the freight, mail, and passengers columns for flights from the United Kingdom to the United States.
filtered_df_cutdown = df_cutdown[(df_cutdown['dest_country'] == 'US') & (df_cutdown['origin_country'] == 'GB')]
filtered_df_cutdown

       origin_country dest_country  passengers    freight  mail
1101               GB           US         0.0   348930.0   0.0
1102               GB           US         0.0    33956.0   0.0
1742               GB           US         0.0  1785444.0   0.0
1743               GB           US         0.0   185326.0   0.0
1753               GB           US         0.0  2004300.0   0.0
...               ...          ...         ...        ...   ...
320984             GB           US     55479.0  4293824.0   0.0
321030             GB           US     56636.0  4161643.0   0.0
321091             GB           US     58359.0  4516041.0   0.0
321114             GB           US     59123.0  4235134.0   0.0
321172             GB           US     61862.0  4715962.0   0.0

[1531 rows x 5 columns]

In [182]:
# 4. Calculate the totals of the freight, mail, and passengers columns for flights from the United Kingdom to the United States.
column_totals = filtered_df_cutdown[['passengers','freight','mail']].sum()
column_totals

passengers     10685608.0
freight       903296879.0
mail           29838395.0
dtype: float64

In [183]:
# 5. Find the top 5 carriers for median route distance (i.e., for all origin-destination pairs that each carrier has, find the median distance after removing duplicates).
df[['distance','unique_carrier_name','origin','dest']]

        distance   unique_carrier_name origin dest
0         8165.0              Emirates    DXB  IAH
1         6849.0              Emirates    DXB  JFK
2         7247.0              Emirates    DXB  ORD
3         8165.0              Emirates    IAH  DXB
4         6849.0              Emirates    JFK  DXB
...          ...                   ...    ...  ...
321404    1448.0  Alaska Airlines Inc.    ANC  SEA
321405    1448.0  Alaska Airlines Inc.    SEA  ANC
321406    1448.0  Alaska Airlines Inc.    ANC  SEA
321407     404.0  Delta Air Lines Inc.    MCO  ATL
321408    1448.0  Alaska Airlines Inc.    SEA  ANC

[321409 rows x 4 columns]

In [184]:
# 5. Find the top 5 carriers for median route distance (i.e., for all origin-destination pairs that each carrier has, find the median distance after removing duplicates).
subset_cols = ['unique_carrier_name','origin','dest']
df_unique = df.drop_duplicates(subset=subset_cols)

df_unique = df_unique[['unique_carrier_name','distance','origin','dest']]
df_unique

           unique_carrier_name  distance origin dest
0                     Emirates    8165.0    DXB  IAH
1                     Emirates    6849.0    DXB  JFK
2                     Emirates    7247.0    DXB  ORD
3                     Emirates    8165.0    IAH  DXB
4                     Emirates    6849.0    JFK  DXB
...                        ...       ...    ...  ...
320471  Hawaiian Airlines Inc.     102.0    HNL  LIH
320479    Alaska Airlines Inc.     954.0    LAX  SEA
320515  Hawaiian Airlines Inc.     163.0    KOA  HNL
320673  American Airlines Inc.    1121.0    DFW  MIA
320831  American Airlines Inc.    1121.0    MIA  DFW

[65988 rows x 4 columns]

In [185]:
# 5. Find the top 5 carriers for median route distance (i.e., for all origin-destination pairs that each carrier has, find the median distance after removing duplicates).
grouped_median = df_unique.groupby('unique_carrier_name').median('distance') 
grouped_median = grouped_median.rename(columns={'distance':'median_distance'})
grouped_median.sort_values('median_distance',ascending=False).head()

                                                    median_distance
unique_carrier_name
Singapore Airlines Ltd.                                      8068.0
Cathay Pacific Airways Ltd.                                  8020.0
Longtail Aviation Ltd.                                       7855.5
Qantas Airways Ltd.                                          7853.0
National Aviation Company of India Limited d/b/...           7707.0

In [186]:
singapore_flights = df_unique.query("unique_carrier_name == 'Singapore Airlines Ltd.'")
singapore_flights.sort_values('distance')

            unique_carrier_name  distance origin dest
1338    Singapore Airlines Ltd.    1567.0    LAX  BRL
49411   Singapore Airlines Ltd.    1947.0    LAX  ATL
132252  Singapore Airlines Ltd.    3856.0    FRA  JFK
151535  Singapore Airlines Ltd.    3856.0    JFK  FRA
1328    Singapore Airlines Ltd.    4426.0    ATL  BRU
189716  Singapore Airlines Ltd.    4714.0    IAH  MAN
196271  Singapore Airlines Ltd.    4714.0    MAN  IAH
1331    Singapore Airlines Ltd.    4959.0    DFW  BRU
49409   Singapore Airlines Ltd.    5081.0    HKG  ANC
229347  Singapore Airlines Ltd.    5451.0    NRT  LAX
227060  Singapore Airlines Ltd.    5451.0    LAX  NRT
1339    Singapore Airlines Ltd.    5639.0    LAX  BRU
44911   Singapore Airlines Ltd.    6005.0    SGN  ANC
215827  Singapore Airlines Ltd.    6927.0    HKG  SFO
206523  Singapore Airlines Ltd.    6927.0    SFO  HKG
1335    Singapore Airlines Ltd.    7260.0    HKG  LAX
19782   Singapore Airlines Ltd.    7260.0    LAX  HKG
39356   Singapore Airlines Ltd.    7600.0    ATL  SHJ
1332    Singapore Airlines Ltd.    8038.0    DFW  SHJ
10924   Singapore Airlines Ltd.    8041.0    HKG  CVG
211667  Singapore Airlines Ltd.    8068.0    SEA  SIN
19787   Singapore Airlines Ltd.    8068.0    SIN  SEA
1334    Singapore Airlines Ltd.    8120.0    HKG  DFW
1340    Singapore Airlines Ltd.    8330.0    LAX  SHJ
293939  Singapore Airlines Ltd.    8440.0    SIN  SFO
290863  Singapore Airlines Ltd.    8440.0    SFO  SIN
1337    Singapore Airlines Ltd.    8698.0    LAX  BOM
1343    Singapore Airlines Ltd.    8758.0    SIN  LAX
1341    Singapore Airlines Ltd.    8758.0    LAX  SIN
1330    Singapore Airlines Ltd.    8781.0    DFW  BOM
15616   Singapore Airlines Ltd.    8983.0    ATL  BLR
1336    Singapore Airlines Ltd.    9000.0    LAX  BLR
44900   Singapore Airlines Ltd.    9133.0    BKK  ATL
223131  Singapore Airlines Ltd.    9485.0    EWR  SIN
228165  Singapore Airlines Ltd.    9485.0    SIN  EWR
139292  Singapore Airlines Ltd.    9487.0    SIN  JFK
148035  Singapore Airlines Ltd.    9487.0    JFK  SIN
1342    Singapore Airlines Ltd.    9642.0    SIN  DFW
1333    Singapore Airlines Ltd.    9642.0    DFW  SIN
157656  Singapore Airlines Ltd.    9838.0    IAH  SIN
158096  Singapore Airlines Ltd.    9838.0    SIN  IAH
1329    Singapore Airlines Ltd.    9866.0    ATL  SIN
44903   Singapore Airlines Ltd.   10314.0    DFW  PER

In [187]:
# 6. Find the total cargo transported (mail + freight) and mean distance traveled for the 10 carriers that transported the most cargo.
df_cargo = df[['freight','mail','distance','unique_carrier_name']]
df_cargo

          freight     mail  distance   unique_carrier_name
0         53185.0      0.0    8165.0              Emirates
1          9002.0      0.0    6849.0              Emirates
2       2220750.0      0.0    7247.0              Emirates
3       1201490.0      0.0    8165.0              Emirates
4        248642.0      0.0    6849.0              Emirates
...           ...      ...       ...                   ...
321404   505308.0  15979.0    1448.0  Alaska Airlines Inc.
321405   473666.0  55963.0    1448.0  Alaska Airlines Inc.
321406   592775.0  18834.0    1448.0  Alaska Airlines Inc.
321407   210292.0   5431.0     404.0  Delta Air Lines Inc.
321408   390399.0  44506.0    1448.0  Alaska Airlines Inc.

[321409 rows x 4 columns]

In [188]:
# 6. Find the total cargo transported (mail + freight) and mean distance traveled for the 10 carriers that transported the most cargo.
df_cargo['cargo'] = df_cargo['freight'] + df_cargo['mail']
df_cargo

C:\Users\TylerHa\AppData\Local\Temp\ipykernel_50160\4272874284.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_cargo['cargo'] = df_cargo['freight'] + df_cargo['mail']

          freight     mail  distance   unique_carrier_name      cargo
0         53185.0      0.0    8165.0              Emirates    53185.0
1          9002.0      0.0    6849.0              Emirates     9002.0
2       2220750.0      0.0    7247.0              Emirates  2220750.0
3       1201490.0      0.0    8165.0              Emirates  1201490.0
4        248642.0      0.0    6849.0              Emirates   248642.0
...           ...      ...       ...                   ...        ...
321404   505308.0  15979.0    1448.0  Alaska Airlines Inc.   521287.0
321405   473666.0  55963.0    1448.0  Alaska Airlines Inc.   529629.0
321406   592775.0  18834.0    1448.0  Alaska Airlines Inc.   611609.0
321407   210292.0   5431.0     404.0  Delta Air Lines Inc.   215723.0
321408   390399.0  44506.0    1448.0  Alaska Airlines Inc.   434905.0

[321409 rows x 5 columns]

In [189]:
# 6. Find the total cargo transported (mail + freight) and mean distance traveled for the 10 carriers that transported the most cargo.
grouped_df_cargo = df_cargo.groupby('unique_carrier_name').agg({'cargo': 'sum', 'distance': 'mean'})
grouped_df_cargo = grouped_df_cargo.rename(columns={'cargo': 'total_cargo','distance': 'mean_distance'})
grouped_df_cargo.sort_values('total_cargo',ascending=False).head(10)

                              total_cargo  mean_distance
unique_carrier_name
Federal Express Corporation  1.270966e+10    1121.887981
United Parcel Service        9.173867e+09    1030.812650
Atlas Air Inc.               3.356847e+09    1900.987202
United Air Lines Inc.        1.577892e+09    1810.656058
American Airlines Inc.       1.353074e+09    1583.185048
Kalitta Air LLC              1.272180e+09    2519.580343
Polar Air Cargo Airways      1.199386e+09    3111.794118
Delta Air Lines Inc.         1.129524e+09    1612.688752
China Airlines Ltd.          8.370799e+08    5828.277778
Cathay Pacific Airways Ltd.  7.741777e+08    7498.685315

In [190]:
# 7. Which 10 carriers flew the most passengers out of the United States to another country?
flights_outof_US = df[(df['origin_country']=='US') & (df['dest_country']!='US')]
flights_outof_US = flights_outof_US[['passengers','unique_carrier_name','origin_country','dest_country']]
flights_outof_US

        passengers  unique_carrier_name origin_country dest_country
3              0.0             Emirates             US           AE
4              0.0             Emirates             US           AE
5              0.0             Emirates             US           AE
10             0.0      Kalitta Air LLC             US           CN
13             0.0      Kalitta Air LLC             US           CN
...            ...                  ...            ...          ...
320933     54317.0  British Airways Plc             US           GB
320956     54776.0  British Airways Plc             US           GB
320962     54886.0  British Airways Plc             US           GB
321051     57313.0  British Airways Plc             US           GB
321112     58959.0  British Airways Plc             US           GB

[35026 rows x 4 columns]

In [191]:
# 7. Which 10 carriers flew the most passengers out of the United States to another country?
flights_outof_US_grouped = flights_outof_US.groupby('unique_carrier_name').sum('passengers')
flights_outof_US_grouped = flights_outof_US_grouped.sort_values('passengers',ascending=False).head(10)
flights_outof_US_grouped

                           passengers
unique_carrier_name
American Airlines Inc.     14867653.0
United Air Lines Inc.      14427923.0
Delta Air Lines Inc.       13054230.0
JetBlue Airways             4522492.0
British Airways Plc         3758945.0
Lufthansa German Airlines   3123611.0
Westjet                     2626600.0
Air Canada                  2540855.0
Southwest Airlines Co.      2146960.0
Virgin Atlantic Airways     2074735.0

In [192]:
# 8. For each of the carriers found in #7, find the most popular destination country outside of the United States.
flights_outof_US_with_dest = flights_outof_US.groupby(['unique_carrier_name', 'dest_country']).agg({'dest_country':'count'})
flights_outof_US_with_dest = flights_outof_US_with_dest.rename(columns={'dest_country':'dest_country_count'})
flights_outof_US_with_dest = flights_outof_US_with_dest.reset_index()
flights_outof_US_with_dest

                       unique_carrier_name dest_country  dest_country_count
0     ABC Aerolineas SA de CV dba Interjet           ID                   1
1     ABC Aerolineas SA de CV dba Interjet           MX                 246
2                             ABS JETS A.S           BM                   1
3                             ABS JETS A.S           CA                   4
4                             ABS JETS A.S           CZ                   2
...                                    ...          ...                 ...
1452                     XL Airways France           FR                  21
1453             Xiamen Airlines Co., Ltd.           CN                  45
1454    Xtra Airlines  dba  Avelo Airlines           CU                  12
1455    Xtra Airlines  dba  Avelo Airlines           DO                   3
1456    Xtra Airlines  dba  Avelo Airlines           KY                  13

[1457 rows x 3 columns]

In [193]:
# 8. For each of the carriers found in #7, find the most popular destination country outside of the United States.
joined_flights = pd.merge(flights_outof_US_grouped,flights_outof_US_with_dest,on='unique_carrier_name',how='left')
joined_flights = joined_flights.sort_values(by=['unique_carrier_name','dest_country_count'], ascending=[True,False])
joined_flights

         unique_carrier_name  passengers dest_country  dest_country_count
207               Air Canada   2540855.0           CA                 523
46    American Airlines Inc.  14867653.0           MX                 312
21    American Airlines Inc.  14867653.0           DO                 132
25    American Airlines Inc.  14867653.0           GB                 125
23    American Airlines Inc.  14867653.0           ES                  99
..                       ...         ...          ...                 ...
119    United Air Lines Inc.  14427923.0           UY                   5
77     United Air Lines Inc.  14427923.0           CW                   1
120    United Air Lines Inc.  14427923.0           ZA                   1
218  Virgin Atlantic Airways   2074735.0           GB                 212
206                  Westjet   2626600.0           CA                 605

[219 rows x 4 columns]

In [194]:
# 8. For each of the carriers found in #7, find the most popular destination country outside of the United States.
most_popular_destinations = joined_flights.groupby('unique_carrier_name').max()
most_popular_destinations = most_popular_destinations.reset_index()
populardropped = most_popular_destinations[['unique_carrier_name','dest_country_count']]
populardropped

         unique_carrier_name  dest_country_count
0                 Air Canada                 523
1     American Airlines Inc.                 312
2        British Airways Plc                 351
3       Delta Air Lines Inc.                 430
4            JetBlue Airways                 207
5  Lufthansa German Airlines                 422
6     Southwest Airlines Co.                 323
7      United Air Lines Inc.                 517
8    Virgin Atlantic Airways                 212
9                    Westjet                 605

In [195]:
# 8. For each of the carriers found in #7, find the most popular destination country outside of the United States.
finaljoin = pd.merge(joined_flights,populardropped,on=['unique_carrier_name','dest_country_count'],how='inner')
finaljoin = finaljoin[['unique_carrier_name','dest_country','dest_country_count']]
finaljoin

         unique_carrier_name dest_country  dest_country_count
0                 Air Canada           CA                 523
1     American Airlines Inc.           MX                 312
2        British Airways Plc           GB                 351
3       Delta Air Lines Inc.           MX                 430
4            JetBlue Airways           DO                 207
5  Lufthansa German Airlines           DE                 422
6     Southwest Airlines Co.           MX                 323
7      United Air Lines Inc.           MX                 517
8    Virgin Atlantic Airways           GB                 212
9                    Westjet           CA                 605

In [196]:
# 9. For each of the carriers found in #7, find the total number of passengers flown on international flights to/from the destinations in #8 or the United States. 
# Note that this dataset only has data for flights with an origin and/or destination of the United States.
destinations_passengers = flights_outof_US.groupby(['unique_carrier_name','dest_country']).sum('passengers')
destinations_passengers

                                                   passengers
unique_carrier_name                  dest_country
ABC Aerolineas SA de CV dba Interjet ID                 373.0
                                     MX             1143628.0
ABS JETS A.S                         BM                   3.0
                                     CA                  22.0
                                     CZ                   5.0
...                                                       ...
XL Airways France                    FR               99114.0
Xiamen Airlines Co., Ltd.            CN              133721.0
Xtra Airlines  dba  Avelo Airlines   CU                4740.0
                                     DO                1576.0
                                     KY                2359.0

[1457 rows x 1 columns]

In [197]:
# 9. For each of the carriers found in #7, find the total number of passengers flown on international flights to/from the destinations in #8 or the United States. 
# Note that this dataset only has data for flights with an origin and/or destination of the United States.
question9_outofUS = pd.merge(finaljoin,destinations_passengers,on=['unique_carrier_name','dest_country'],how='inner')
question9_outofUS = question9_outofUS.rename(columns={'passengers':'passengers_outofUS','dest_country': 'join_country'})
question9_outofUS = question9_outofUS[['unique_carrier_name','join_country','passengers_outofUS']]
question9_outofUS

         unique_carrier_name join_country  passengers_outofUS
0                 Air Canada           CA           2540855.0
1     American Airlines Inc.           MX           2424606.0
2        British Airways Plc           GB           3758945.0
3       Delta Air Lines Inc.           MX           1872840.0
4            JetBlue Airways           DO           1413023.0
5  Lufthansa German Airlines           DE           3123209.0
6     Southwest Airlines Co.           MX           1001375.0
7      United Air Lines Inc.           MX           2201389.0
8    Virgin Atlantic Airways           GB           2074735.0
9                    Westjet           CA           2626600.0

In [198]:
# 9. For each of the carriers found in #7, find the total number of passengers flown on international flights to/from the destinations in #8 or the United States. 
# Note that this dataset only has data for flights with an origin and/or destination of the United States.
flights_to_US = df[(df['origin_country']!='US') & (df['dest_country']=='US')]
flights_to_US = flights_to_US[['passengers','unique_carrier_name','origin_country','dest_country']]
flights_to_US = flights_to_US.rename(columns={'origin_country':'join_country'})
flights_to_US

        passengers  unique_carrier_name join_country dest_country
0              0.0             Emirates           AE           US
1              0.0             Emirates           AE           US
2              0.0             Emirates           AE           US
15             0.0      Kalitta Air LLC           CN           US
30             0.0      Kalitta Air LLC           HK           US
...            ...                  ...          ...          ...
320984     55479.0  British Airways Plc           GB           US
321030     56636.0  British Airways Plc           GB           US
321091     58359.0  British Airways Plc           GB           US
321114     59123.0  British Airways Plc           GB           US
321172     61862.0  British Airways Plc           GB           US

[34269 rows x 4 columns]

In [199]:
# 9. For each of the carriers found in #7, find the total number of passengers flown on international flights to/from the destinations in #8 or the United States. 
# Note that this dataset only has data for flights with an origin and/or destination of the United States.
flights_to_US_grouped = flights_to_US.groupby(['unique_carrier_name','join_country']).sum('passengers')
flights_to_US_grouped = flights_to_US_grouped.sort_values('passengers',ascending=False)
flights_to_US_grouped

                                                     passengers
unique_carrier_name                    join_country
British Airways Plc                    GB             3772399.0
Lufthansa German Airlines              DE             3174624.0
Westjet                                CA             2647227.0
Air Canada                             CA             2503234.0
American Airlines Inc.                 MX             2400671.0
...                                                         ...
Sky Lease Cargo                        AR                   0.0
Singapore Airlines Ltd.                VN                   0.0
                                       TH                   0.0
Federal Express Corporation            AE                   0.0
Yangtze River Express Airlines Company CN                   0.0

[1393 rows x 1 columns]

In [200]:
# 9. For each of the carriers found in #7, find the total number of passengers flown on international flights to/from the destinations in #8 or the United States. 
# Note that this dataset only has data for flights with an origin and/or destination of the United States.
question9_final = pd.merge(question9_outofUS,flights_to_US_grouped,on=['unique_carrier_name','join_country'],how='inner')
question9_final = question9_final.rename(columns={'join_country':'country', 'passengers':'passengers_toUS'})
question9_final

         unique_carrier_name country  passengers_outofUS  passengers_toUS
0                 Air Canada      CA           2540855.0        2503234.0
1     American Airlines Inc.      MX           2424606.0        2400671.0
2        British Airways Plc      GB           3758945.0        3772399.0
3       Delta Air Lines Inc.      MX           1872840.0        1864259.0
4            JetBlue Airways      DO           1413023.0        1428552.0
5  Lufthansa German Airlines      DE           3123209.0        3174624.0
6     Southwest Airlines Co.      MX           1001375.0         994830.0
7      United Air Lines Inc.      MX           2201389.0        2187791.0
8    Virgin Atlantic Airways      GB           2074735.0        2065355.0
9                    Westjet      CA           2626600.0        2647227.0

In [201]:
# 10. Between which two cities were the most passengers flown? Make sure to account for both directions.
travel_cities = df[['passengers','origin_city_name','dest_city_name']]
travel_cities

        passengers             origin_city_name               dest_city_name
0              0.0  Dubai, United Arab Emirates                  Houston, TX
1              0.0  Dubai, United Arab Emirates                 New York, NY
2              0.0  Dubai, United Arab Emirates                  Chicago, IL
3              0.0                  Houston, TX  Dubai, United Arab Emirates
4              0.0                 New York, NY  Dubai, United Arab Emirates
...            ...                          ...                          ...
321404     96984.0                Anchorage, AK                  Seattle, WA
321405     97011.0                  Seattle, WA                Anchorage, AK
321406     97098.0                Anchorage, AK                  Seattle, WA
321407     97329.0                  Orlando, FL                  Atlanta, GA
321408     97644.0                  Seattle, WA                Anchorage, AK

[321409 rows x 3 columns]

In [202]:
# 10. Between which two cities were the most passengers flown? Make sure to account for both directions.
grouped_travel_cities = travel_cities.groupby(['origin_city_name','dest_city_name']).sum('passengers')
grouped_travel_cities = grouped_travel_cities.sort_values('passengers',ascending=False).head(2)
grouped_travel_cities

                                 passengers
origin_city_name dest_city_name
Chicago, IL      New York, NY     2067068.0
New York, NY     Chicago, IL      2064511.0

In [211]:
# 11. Find the top 3 carriers for the pair of cities found in #10 and calculate the percentage of passengers each accounted for.
carrier_cities = df[['unique_carrier_name','origin_city_name','dest_city_name','passengers']]
carrier_cities = carrier_cities.groupby(['unique_carrier_name','origin_city_name','dest_city_name']).sum('passengers')
carrier_cities = carrier_cities.sort_values('passengers',ascending=False)
carrier_cities

                                                                         passengers
unique_carrier_name                    origin_city_name dest_city_name
Delta Air Lines Inc.                   Atlanta, GA      New York, NY      1246893.0
                                       New York, NY     Atlanta, GA       1243670.0
                                       Orlando, FL      Atlanta, GA       1077446.0
                                       Atlanta, GA      Orlando, FL       1073975.0
Hawaiian Airlines Inc.                 Kahului, HI      Honolulu, HI       918286.0
...                                                                             ...
Federal Express Corporation            Indianapolis, IN Yakima, WA              0.0
                                       Inyokern, CA     Bishop, CA              0.0
                                                        Farmington, NM          0.0
                                                        Great Falls, MT         0.0
Yangtze River Express Airlines Company Shanghai, China  Chicago, IL             0.0

[64316 rows x 1 columns]

In [212]:
# 11. Find the top 3 carriers for the pair of cities found in #10 and calculate the percentage of passengers each accounted for.
carrier_cities = carrier_cities.reset_index()
carrier_cities

,unique_carrier_name,origin_city_name,dest_city_name,passengers
0,Delta Air Lines Inc.,"Atlanta, GA","New York, NY",1246893.0
1,Delta Air Lines Inc.,"New York, NY","Atlanta, GA",1243670.0
2,Delta Air Lines Inc.,"Orlando, FL","Atlanta, GA",1077446.0
3,Delta Air Lines Inc.,"Atlanta, GA","Orlando, FL",1073975.0
4,Hawaiian Airlines Inc.,"Kahului, HI","Honolulu, HI",918286.0
...,...,...,...,...
64311,Federal Express Corporation,"Indianapolis, IN","Yakima, WA",0.0
64312,Federal Express Corporation,"Inyokern, CA","Bishop, CA",0.0
64313,Federal Express Corporation,"Inyokern, CA","Farmington, NM",0.0
64314,Federal Express Corporation,"Inyokern, CA","Great Falls, MT",0.0
64315,Yangtze River Express Airlines Company,"Shanghai, China","Chicago, IL",0.0

In [220]:
# 11. Find the top 3 carriers for the pair of cities found in #10 and calculate the percentage of passengers each accounted for.
filtered_carrier_cities = carrier_cities[carrier_cities['origin_city_name'].isin(['New York, NY','Chicago, IL']) 
                                         & carrier_cities['dest_city_name'].isin(['New York, NY','Chicago, IL'])]
filtered_carrier_cities

,unique_carrier_name,origin_city_name,dest_city_name,passengers
43,American Airlines Inc.,"Chicago, IL","New York, NY",654594.0
51,American Airlines Inc.,"New York, NY","Chicago, IL",638801.0
156,United Air Lines Inc.,"New York, NY","Chicago, IL",481592.0
160,United Air Lines Inc.,"Chicago, IL","New York, NY",478065.0
559,Delta Air Lines Inc.,"New York, NY","Chicago, IL",277249.0
574,Delta Air Lines Inc.,"Chicago, IL","New York, NY",273633.0
656,Southwest Airlines Co.,"Chicago, IL","New York, NY",257302.0
669,Southwest Airlines Co.,"New York, NY","Chicago, IL",255561.0
2031,SkyWest Airlines Inc.,"New York, NY","Chicago, IL",126431.0
2131,SkyWest Airlines Inc.,"Chicago, IL","New York, NY",121946.0
2266,Spirit Air Lines,"New York, NY","Chicago, IL",115747.0
2294,Spirit Air Lines,"Chicago, IL","New York, NY",114686.0
4639,JetBlue Airways,"New York, NY","Chicago, IL",66090.0
4645,JetBlue Airways,"Chicago, IL","New York, NY",66000.0
4685,Endeavor Air Inc.,"New York, NY","Chicago, IL",65505.0
4858,Endeavor Air Inc.,"Chicago, IL","New York, NY",62990.0
8788,Republic Airline,"Chicago, IL","New York, NY",30285.0
8910,Republic Airline,"New York, NY","Chicago, IL",29608.0
14372,ExpressJet Airlines LLC,"New York, NY","Chicago, IL",7919.0
14559,ExpressJet Airlines LLC,"Chicago, IL","New York, NY",7489.0
19879,JetBlue Airways,"New York, NY","New York, NY",811.0
29516,Envoy Air,"Chicago, IL","New York, NY",76.0
33891,American Airlines Inc.,"New York, NY","New York, NY",32.0
34400,Envoy Air,"New York, NY","New York, NY",27.0
38034,"Jet Aviation Flight Services, Inc.","New York, NY","Chicago, IL",8.0
39533,"Jet Aviation Flight Services, Inc.","New York, NY","New York, NY",6.0
41451,"Jet Aviation Flight Services, Inc.","Chicago, IL","Chicago, IL",4.0
44488,"Jet Aviation Flight Services, Inc.","Chicago, IL","New York, NY",2.0
45464,Delta Air Lines Inc.,"New York, NY","New York, NY",2.0
47582,Turk Hava Yollari A.O.,"New York, NY","Chicago, IL",0.0
51827,Western Global,"Chicago, IL","Chicago, IL",0.0
52822,Atlas Air Inc.,"New York, NY","New York, NY",0.0
53717,Atlas Air Inc.,"Chicago, IL","New York, NY",0.0
53780,Atlas Air Inc.,"Chicago, IL","Chicago, IL",0.0
54077,Atlas Air Inc.,"New York, NY","Chicago, IL",0.0
55528,Kalitta Air LLC,"Chicago, IL","New York, NY",0.0
57297,Miami Air International,"New York, NY","Chicago, IL",0.0
57313,Miami Air International,"New York, NY","New York, NY",0.0
57912,Polar Air Cargo Airways,"Chicago, IL","Chicago, IL",0.0
58072,Sky Lease Cargo,"Chicago, IL","New York, NY",0.0
58511,Southern Air Inc.,"New York, NY","Chicago, IL",0.0
58861,Miami Air International,"Chicago, IL","Chicago, IL",0.0
60082,Federal Express Corporation,"Chicago, IL","Chicago, IL",0.0
61890,Federal Express Corporation,"New York, NY","New York, NY",0.0

In [327]:
# 11. Find the top 3 carriers for the pair of cities found in #10 and calculate the percentage of passengers each accounted for.
summed_carrier_cities = filtered_carrier_cities.groupby('unique_carrier_name').sum('passengers')
summed_carrier_cities = summed_carrier_cities.sort_values('passengers',ascending=False)
summed_carrier_cities

                                    passengers
unique_carrier_name
American Airlines Inc.               1293427.0
United Air Lines Inc.                 959657.0
Delta Air Lines Inc.                  550884.0
Southwest Airlines Co.                512863.0
SkyWest Airlines Inc.                 248377.0
Spirit Air Lines                      230433.0
JetBlue Airways                       132901.0
Endeavor Air Inc.                     128495.0
Republic Airline                       59893.0
ExpressJet Airlines LLC                15408.0
Envoy Air                                103.0
Jet Aviation Flight Services, Inc.        20.0
Turk Hava Yollari A.O.                     0.0
Southern Air Inc.                          0.0
Miami Air International                    0.0
Sky Lease Cargo                            0.0
Polar Air Cargo Airways                    0.0
Atlas Air Inc.                             0.0
Kalitta Air LLC                            0.0
Federal Express Corporation                0.0
Western Global                             0.0

In [338]:
# 11. Find the top 3 carriers for the pair of cities found in #10 and calculate the percentage of passengers each accounted for.
total_passengers = summed_carrier_cities['passengers'].sum()
summed_carrier_cities['percent_of_total'] = (summed_carrier_cities['passengers']/total_passengers)*100
summed_carrier_cities = summed_carrier_cities.head(3)
summed_carrier_cities

                        passengers  percent_of_total
unique_carrier_name
American Airlines Inc.   1293427.0         31.299194
United Air Lines Inc.     959657.0         23.222409
Delta Air Lines Inc.      550884.0         13.330652

In [ ]:
# 12. Find the percentage of international travel per country using total passengers on class F flights.
question12 = df[['passengers','origin_country_name','dest_country_name','class']]
question12 = question12[question12['class']=='F']
question12_international = question12[question12['origin_country_name'] != question12['dest_country_name']]
question12_international

        passengers     origin_country_name       dest_country_name class
2251           0.0  British Virgin Islands           United States     F
2262           0.0           United States  British Virgin Islands     F
2263           0.0           United States  British Virgin Islands     F
2264           0.0  British Virgin Islands           United States     F
2313           0.0           United States                  Canada     F
...            ...                     ...                     ...   ...
321051     57313.0           United States          United Kingdom     F
321091     58359.0          United Kingdom           United States     F
321112     58959.0           United States          United Kingdom     F
321114     59123.0          United Kingdom           United States     F
321172     61862.0          United Kingdom           United States     F

[49786 rows x 4 columns]

In [303]:
# 12. Find the percentage of international travel per country using total passengers on class F flights.
grouped_question12 = question12.groupby(['origin_country_name','dest_country_name']).sum('passengers')
grouped_question12 = grouped_question12.reset_index()
grouped_question12

     origin_country_name dest_country_name  passengers
0               Anguilla     United States      5934.0
1    Antigua and Barbuda     United States    154718.0
2              Argentina     United States    914918.0
3                  Aruba     United States    898269.0
4              Australia     United States   1660902.0
..                   ...               ...         ...
212        United States        Uzbekistan     27351.0
213        United States         Venezuela     42664.0
214              Uruguay     United States     59006.0
215           Uzbekistan     United States     28579.0
216            Venezuela     United States     41444.0

[217 rows x 3 columns]

In [308]:
# 12. Find the percentage of international travel per country using total passengers on class F flights.
grouped_question12['other_country'] = np.where(grouped_question12['dest_country_name']=='United States',grouped_question12['origin_country_name'],grouped_question12['dest_country_name'])
grouped_question12

     origin_country_name dest_country_name  passengers        other_country
0               Anguilla     United States      5934.0             Anguilla
1    Antigua and Barbuda     United States    154718.0  Antigua and Barbuda
2              Argentina     United States    914918.0            Argentina
3                  Aruba     United States    898269.0                Aruba
4              Australia     United States   1660902.0            Australia
..                   ...               ...         ...                  ...
212        United States        Uzbekistan     27351.0           Uzbekistan
213        United States         Venezuela     42664.0            Venezuela
214              Uruguay     United States     59006.0              Uruguay
215           Uzbekistan     United States     28579.0           Uzbekistan
216            Venezuela     United States     41444.0            Venezuela

[217 rows x 4 columns]

In [318]:
# 12. Find the percentage of international travel per country using total passengers on class F flights.
regrouped_question12 = grouped_question12.groupby('other_country').sum('passengers')
regrouped_question12
index_to_exclude = 'United States'
regrouped_question12 = regrouped_question12.drop(index_to_exclude)
regrouped_question12

                      passengers
other_country
Anguilla                 11900.0
Antigua and Barbuda     311494.0
Argentina              1811324.0
Aruba                  1799959.0
Australia              3321194.0
...                          ...
United Arab Emirates   3865182.0
United Kingdom        21425827.0
Uruguay                 117876.0
Uzbekistan               55930.0
Venezuela                84108.0

[109 rows x 1 columns]

In [371]:
# 12. Find the percentage of international travel per country using total passengers on class F flights.
q12_total = regrouped_question12['passengers'].sum()
regrouped_question12['percent_of_total'] = (regrouped_question12['passengers'] / q12_total)*100
regrouped_question12 = regrouped_question12.sort_values('percent_of_total',ascending=False)
regrouped_question12

                passengers  percent_of_total
other_country
Canada          31770651.0         13.159041
Mexico          30733526.0         12.729475
United Kingdom  21425827.0          8.874333
Germany         10887684.0          4.509554
Japan           10010159.0          4.146093
...                    ...               ...
Kiribati            2929.0          0.001213
Suriname            2546.0          0.001055
Tonga                579.0          0.000240
Indonesia            373.0          0.000154
New Caledonia        237.0          0.000098

[109 rows x 2 columns]

In [360]:
# 13. Using a crosstab, find the percentage of total passengers on class F international flights between US cities and the countries found in #12 that used the carriers found in #11.
question13 = df[['unique_carrier_name','passengers','origin_city_name','origin_country_name','dest_city_name','dest_country_name','class']]
question13 = question13[(question13['class']=='F')&(question13['origin_country_name']!=question13['dest_country_name'])]
question13_joined = pd.merge(summed_carrier_cities,question13,on=['unique_carrier_name'],how='inner')
question13_joined = question13_joined.drop(columns=['passengers_x','percent_of_total'])
question13_joined

,unique_carrier_name,passengers_y,origin_city_name,origin_country_name,dest_city_name,dest_country_name,class
0,American Airlines Inc.,1.0,"Guatemala City, Guatemala",Guatemala,"Los Angeles, CA",United States,F
1,American Airlines Inc.,1.0,"Dallas/Fort Worth, TX",United States,"Panama City, Panama",Panama,F
2,American Airlines Inc.,1.0,"Frankfurt, Germany",Germany,"Chicago, IL",United States,F
3,American Airlines Inc.,1.0,"London, United Kingdom",United Kingdom,"Houston, TX",United States,F
4,American Airlines Inc.,1.0,"Cancun, Mexico",Mexico,"Houston, TX",United States,F
...,...,...,...,...,...,...,...
16559,Delta Air Lines Inc.,32172.0,"Atlanta, GA",United States,"Cancun, Mexico",Mexico,F
16560,Delta Air Lines Inc.,32184.0,"Cancun, Mexico",Mexico,"Atlanta, GA",United States,F
16561,Delta Air Lines Inc.,32350.0,"Atlanta, GA",United States,"Cancun, Mexico",Mexico,F
16562,Delta Air Lines Inc.,32361.0,"Detroit, MI",United States,"Amsterdam, Netherlands",Netherlands,F
16563,Delta Air Lines Inc.,33015.0,"Cancun, Mexico",Mexico,"Atlanta, GA",United States,F

In [361]:
# 13. Using a crosstab, find the percentage of total passengers on class F international flights between US cities and the countries found in #12 that used the carriers found in #11.
question13_joined['other_country'] = np.where(question13_joined['dest_country_name']=='United States',question13_joined['origin_country_name'],question13_joined['dest_country_name'])
question13_joined['US_city'] = np.where(question13_joined['dest_country_name']=='United States',question13_joined['dest_city_name'],question13_joined['origin_city_name'])
question13_joined = question13_joined.drop(columns=['origin_city_name','origin_country_name','dest_city_name','dest_country_name','class'])
question13_joined

,unique_carrier_name,passengers_y,other_country,US_city
0,American Airlines Inc.,1.0,Guatemala,"Los Angeles, CA"
1,American Airlines Inc.,1.0,Panama,"Dallas/Fort Worth, TX"
2,American Airlines Inc.,1.0,Germany,"Chicago, IL"
3,American Airlines Inc.,1.0,United Kingdom,"Houston, TX"
4,American Airlines Inc.,1.0,Mexico,"Houston, TX"
...,...,...,...,...
16559,Delta Air Lines Inc.,32172.0,Mexico,"Atlanta, GA"
16560,Delta Air Lines Inc.,32184.0,Mexico,"Atlanta, GA"
16561,Delta Air Lines Inc.,32350.0,Mexico,"Atlanta, GA"
16562,Delta Air Lines Inc.,32361.0,Netherlands,"Detroit, MI"
16563,Delta Air Lines Inc.,33015.0,Mexico,"Atlanta, GA"

In [364]:
# 13. Using a crosstab, find the percentage of total passengers on class F international flights between US cities and the countries found in #12 that used the carriers found in #11.
question13_joined.reset_index()
question13_joinedgrouped = question13_joined.groupby(['unique_carrier_name','other_country','US_city']).sum('passengers_y')
question13_joinedgrouped

                                                                  passengers_y
unique_carrier_name    other_country       US_city
American Airlines Inc. Antigua and Barbuda Charlotte, NC                9097.0
                                           Miami, FL                  125082.0
                                           New York, NY                76047.0
                                           San Juan, PR                   43.0
                       Argentina           Dallas/Fort Worth, TX      153531.0
...                                                                        ...
United Air Lines Inc.  United Kingdom      San Francisco, CA          339090.0
                                           Syracuse, NY                    0.0
                                           Washington, DC             392088.0
                       Uruguay             Houston, TX                     0.0
                                           Newark, NJ                      0.0

[1150 rows x 1 columns]