In [32]:
import pandas as pd
import numpy as np
df = pd.read_csv(r"C:\Users\TylerHa\Documents\GitHub\Python\Data\865214564_T_T100_MARKET_ALL_CARRIER.csv")

df

,PASSENGERS,FREIGHT,MAIL,DISTANCE,UNIQUE_CARRIER,AIRLINE_ID,UNIQUE_CARRIER_NAME,UNIQUE_CARRIER_ENTITY,REGION,CARRIER,...,DEST_STATE_NM,DEST_COUNTRY,DEST_COUNTRY_NAME,DEST_WAC,YEAR,QUARTER,MONTH,DISTANCE_GROUP,CLASS,DATA_SOURCE
0,0.0,53185.0,0.0,8165.0,EK,20392,Emirates,9678A,I,EK,...,Texas,US,United States,74,2019,1,3,17,G,IF
1,0.0,9002.0,0.0,6849.0,EK,20392,Emirates,9678A,I,EK,...,New York,US,United States,22,2019,1,3,14,G,IF
2,0.0,2220750.0,0.0,7247.0,EK,20392,Emirates,9678A,I,EK,...,Illinois,US,United States,41,2019,1,3,15,G,IF
3,0.0,1201490.0,0.0,8165.0,EK,20392,Emirates,9678A,I,EK,...,NaN,AE,United Arab Emirates,678,2019,1,3,17,G,IF
4,0.0,248642.0,0.0,6849.0,EK,20392,Emirates,9678A,I,EK,...,NaN,AE,United Arab Emirates,678,2019,1,3,14,G,IF
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
321404,96984.0,505308.0,15979.0,1448.0,AS,19930,Alaska Airlines Inc.,06031,D,AS,...,Washington,US,United States,93,2019,3,7,3,F,DU
321405,97011.0,473666.0,55963.0,1448.0,AS,19930,Alaska Airlines Inc.,06031,D,AS,...,Alaska,US,United States,1,2019,2,6,3,F,DU
321406,97098.0,592775.0,18834.0,1448.0,AS,19930,Alaska Airlines Inc.,06031,D,AS,...,Washington,US,United States,93,2019,3,8,3,F,DU
321407,97329.0,210292.0,5431.0,404.0,DL,19790,Delta Air Lines Inc.,01260,D,DL,...,Georgia,US,United States,34,2019,1,3,1,F,DU
321408,97644.0,390399.0,44506.0,1448.0,AS,19930,Alaska Airlines Inc.,06031,D,AS,...,Alaska,US,United States,1,2019,3,7,3,F,DU

In [37]:
# 1. Read in the data and convert the column names to lowercase to make them easier to work with.
df.columns = df.columns.str.lower()
df

,passengers,freight,mail,distance,unique_carrier,airline_id,unique_carrier_name,unique_carrier_entity,region,carrier,...,dest_state_nm,dest_country,dest_country_name,dest_wac,year,quarter,month,distance_group,class,data_source
0,0.0,53185.0,0.0,8165.0,EK,20392,Emirates,9678A,I,EK,...,Texas,US,United States,74,2019,1,3,17,G,IF
1,0.0,9002.0,0.0,6849.0,EK,20392,Emirates,9678A,I,EK,...,New York,US,United States,22,2019,1,3,14,G,IF
2,0.0,2220750.0,0.0,7247.0,EK,20392,Emirates,9678A,I,EK,...,Illinois,US,United States,41,2019,1,3,15,G,IF
3,0.0,1201490.0,0.0,8165.0,EK,20392,Emirates,9678A,I,EK,...,NaN,AE,United Arab Emirates,678,2019,1,3,17,G,IF
4,0.0,248642.0,0.0,6849.0,EK,20392,Emirates,9678A,I,EK,...,NaN,AE,United Arab Emirates,678,2019,1,3,14,G,IF
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
321404,96984.0,505308.0,15979.0,1448.0,AS,19930,Alaska Airlines Inc.,06031,D,AS,...,Washington,US,United States,93,2019,3,7,3,F,DU
321405,97011.0,473666.0,55963.0,1448.0,AS,19930,Alaska Airlines Inc.,06031,D,AS,...,Alaska,US,United States,1,2019,2,6,3,F,DU
321406,97098.0,592775.0,18834.0,1448.0,AS,19930,Alaska Airlines Inc.,06031,D,AS,...,Washington,US,United States,93,2019,3,8,3,F,DU
321407,97329.0,210292.0,5431.0,404.0,DL,19790,Delta Air Lines Inc.,01260,D,DL,...,Georgia,US,United States,34,2019,1,3,1,F,DU
321408,97644.0,390399.0,44506.0,1448.0,AS,19930,Alaska Airlines Inc.,06031,D,AS,...,Alaska,US,United States,1,2019,3,7,3,F,DU

In [38]:
# 2. What columns are in the data?
df.columns

Index(['passengers', 'freight', 'mail', 'distance', 'unique_carrier',
       'airline_id', 'unique_carrier_name', 'unique_carrier_entity', 'region',
       'carrier', 'carrier_name', 'carrier_group', 'carrier_group_new',
       'origin_airport_id', 'origin_airport_seq_id', 'origin_city_market_id',
       'origin', 'origin_city_name', 'origin_state_abr', 'origin_state_fips',
       'origin_state_nm', 'origin_country', 'origin_country_name',
       'origin_wac', 'dest_airport_id', 'dest_airport_seq_id',
       'dest_city_market_id', 'dest', 'dest_city_name', 'dest_state_abr',
       'dest_state_fips', 'dest_state_nm', 'dest_country', 'dest_country_name',
       'dest_wac', 'year', 'quarter', 'month', 'distance_group', 'class',
       'data_source'],
      dtype='object')

In [39]:
# 3. How many distinct carrier names are in the dataset?
carrier_count = df['carrier'].nunique()
carrier_count

319

In [55]:
# 4. Calculate the totals of the freight, mail, and passengers columns for flights from the United Kingdom to the United States.
df_cutdown = df[['origin_country','dest_country','passengers','freight','mail']]
df_cutdown

       origin_country dest_country  passengers    freight     mail
0                  AE           US         0.0    53185.0      0.0
1                  AE           US         0.0     9002.0      0.0
2                  AE           US         0.0  2220750.0      0.0
3                  US           AE         0.0  1201490.0      0.0
4                  US           AE         0.0   248642.0      0.0
...               ...          ...         ...        ...      ...
321404             US           US     96984.0   505308.0  15979.0
321405             US           US     97011.0   473666.0  55963.0
321406             US           US     97098.0   592775.0  18834.0
321407             US           US     97329.0   210292.0   5431.0
321408             US           US     97644.0   390399.0  44506.0

[321409 rows x 5 columns]

In [56]:
# 4. Calculate the totals of the freight, mail, and passengers columns for flights from the United Kingdom to the United States.
filtered_df_cutdown = df_cutdown[(df_cutdown['dest_country'] == 'US') & (df_cutdown['origin_country'] == 'GB')]
filtered_df_cutdown

       origin_country dest_country  passengers    freight  mail
1101               GB           US         0.0   348930.0   0.0
1102               GB           US         0.0    33956.0   0.0
1742               GB           US         0.0  1785444.0   0.0
1743               GB           US         0.0   185326.0   0.0
1753               GB           US         0.0  2004300.0   0.0
...               ...          ...         ...        ...   ...
320984             GB           US     55479.0  4293824.0   0.0
321030             GB           US     56636.0  4161643.0   0.0
321091             GB           US     58359.0  4516041.0   0.0
321114             GB           US     59123.0  4235134.0   0.0
321172             GB           US     61862.0  4715962.0   0.0

[1531 rows x 5 columns]

In [ ]:
# 4. Calculate the totals of the freight, mail, and passengers columns for flights from the United Kingdom to the United States.
column_totals = filtered_df_cutdown[['passengers','freight','mail']].sum()
column_totals

passengers     10685608.0
freight       903296879.0
mail           29838395.0
dtype: float64