In [1]:
import pandas as pd
import numpy as np
df = pd.read_csv(r"C:\Users\TylerHa\Documents\GitHub\Python\Data\865214564_T_T100_MARKET_ALL_CARRIER.csv")

df

,PASSENGERS,FREIGHT,MAIL,DISTANCE,UNIQUE_CARRIER,AIRLINE_ID,UNIQUE_CARRIER_NAME,UNIQUE_CARRIER_ENTITY,REGION,CARRIER,...,DEST_STATE_NM,DEST_COUNTRY,DEST_COUNTRY_NAME,DEST_WAC,YEAR,QUARTER,MONTH,DISTANCE_GROUP,CLASS,DATA_SOURCE
0,0.0,53185.0,0.0,8165.0,EK,20392,Emirates,9678A,I,EK,...,Texas,US,United States,74,2019,1,3,17,G,IF
1,0.0,9002.0,0.0,6849.0,EK,20392,Emirates,9678A,I,EK,...,New York,US,United States,22,2019,1,3,14,G,IF
2,0.0,2220750.0,0.0,7247.0,EK,20392,Emirates,9678A,I,EK,...,Illinois,US,United States,41,2019,1,3,15,G,IF
3,0.0,1201490.0,0.0,8165.0,EK,20392,Emirates,9678A,I,EK,...,NaN,AE,United Arab Emirates,678,2019,1,3,17,G,IF
4,0.0,248642.0,0.0,6849.0,EK,20392,Emirates,9678A,I,EK,...,NaN,AE,United Arab Emirates,678,2019,1,3,14,G,IF
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
321404,96984.0,505308.0,15979.0,1448.0,AS,19930,Alaska Airlines Inc.,06031,D,AS,...,Washington,US,United States,93,2019,3,7,3,F,DU
321405,97011.0,473666.0,55963.0,1448.0,AS,19930,Alaska Airlines Inc.,06031,D,AS,...,Alaska,US,United States,1,2019,2,6,3,F,DU
321406,97098.0,592775.0,18834.0,1448.0,AS,19930,Alaska Airlines Inc.,06031,D,AS,...,Washington,US,United States,93,2019,3,8,3,F,DU
321407,97329.0,210292.0,5431.0,404.0,DL,19790,Delta Air Lines Inc.,01260,D,DL,...,Georgia,US,United States,34,2019,1,3,1,F,DU
321408,97644.0,390399.0,44506.0,1448.0,AS,19930,Alaska Airlines Inc.,06031,D,AS,...,Alaska,US,United States,1,2019,3,7,3,F,DU

In [2]:
# 1. Read in the data and convert the column names to lowercase to make them easier to work with.
df.columns = df.columns.str.lower()
df

,passengers,freight,mail,distance,unique_carrier,airline_id,unique_carrier_name,unique_carrier_entity,region,carrier,...,dest_state_nm,dest_country,dest_country_name,dest_wac,year,quarter,month,distance_group,class,data_source
0,0.0,53185.0,0.0,8165.0,EK,20392,Emirates,9678A,I,EK,...,Texas,US,United States,74,2019,1,3,17,G,IF
1,0.0,9002.0,0.0,6849.0,EK,20392,Emirates,9678A,I,EK,...,New York,US,United States,22,2019,1,3,14,G,IF
2,0.0,2220750.0,0.0,7247.0,EK,20392,Emirates,9678A,I,EK,...,Illinois,US,United States,41,2019,1,3,15,G,IF
3,0.0,1201490.0,0.0,8165.0,EK,20392,Emirates,9678A,I,EK,...,NaN,AE,United Arab Emirates,678,2019,1,3,17,G,IF
4,0.0,248642.0,0.0,6849.0,EK,20392,Emirates,9678A,I,EK,...,NaN,AE,United Arab Emirates,678,2019,1,3,14,G,IF
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
321404,96984.0,505308.0,15979.0,1448.0,AS,19930,Alaska Airlines Inc.,06031,D,AS,...,Washington,US,United States,93,2019,3,7,3,F,DU
321405,97011.0,473666.0,55963.0,1448.0,AS,19930,Alaska Airlines Inc.,06031,D,AS,...,Alaska,US,United States,1,2019,2,6,3,F,DU
321406,97098.0,592775.0,18834.0,1448.0,AS,19930,Alaska Airlines Inc.,06031,D,AS,...,Washington,US,United States,93,2019,3,8,3,F,DU
321407,97329.0,210292.0,5431.0,404.0,DL,19790,Delta Air Lines Inc.,01260,D,DL,...,Georgia,US,United States,34,2019,1,3,1,F,DU
321408,97644.0,390399.0,44506.0,1448.0,AS,19930,Alaska Airlines Inc.,06031,D,AS,...,Alaska,US,United States,1,2019,3,7,3,F,DU

In [3]:
# 2. What columns are in the data?
df.columns

Index(['passengers', 'freight', 'mail', 'distance', 'unique_carrier',
       'airline_id', 'unique_carrier_name', 'unique_carrier_entity', 'region',
       'carrier', 'carrier_name', 'carrier_group', 'carrier_group_new',
       'origin_airport_id', 'origin_airport_seq_id', 'origin_city_market_id',
       'origin', 'origin_city_name', 'origin_state_abr', 'origin_state_fips',
       'origin_state_nm', 'origin_country', 'origin_country_name',
       'origin_wac', 'dest_airport_id', 'dest_airport_seq_id',
       'dest_city_market_id', 'dest', 'dest_city_name', 'dest_state_abr',
       'dest_state_fips', 'dest_state_nm', 'dest_country', 'dest_country_name',
       'dest_wac', 'year', 'quarter', 'month', 'distance_group', 'class',
       'data_source'],
      dtype='object')

In [4]:
# 3. How many distinct carrier names are in the dataset?
carrier_count = df['carrier'].nunique()
carrier_count

319

In [5]:
# 4. Calculate the totals of the freight, mail, and passengers columns for flights from the United Kingdom to the United States.
df_cutdown = df[['origin_country','dest_country','passengers','freight','mail']]
df_cutdown

       origin_country dest_country  passengers    freight     mail
0                  AE           US         0.0    53185.0      0.0
1                  AE           US         0.0     9002.0      0.0
2                  AE           US         0.0  2220750.0      0.0
3                  US           AE         0.0  1201490.0      0.0
4                  US           AE         0.0   248642.0      0.0
...               ...          ...         ...        ...      ...
321404             US           US     96984.0   505308.0  15979.0
321405             US           US     97011.0   473666.0  55963.0
321406             US           US     97098.0   592775.0  18834.0
321407             US           US     97329.0   210292.0   5431.0
321408             US           US     97644.0   390399.0  44506.0

[321409 rows x 5 columns]

In [6]:
# 4. Calculate the totals of the freight, mail, and passengers columns for flights from the United Kingdom to the United States.
filtered_df_cutdown = df_cutdown[(df_cutdown['dest_country'] == 'US') & (df_cutdown['origin_country'] == 'GB')]
filtered_df_cutdown

       origin_country dest_country  passengers    freight  mail
1101               GB           US         0.0   348930.0   0.0
1102               GB           US         0.0    33956.0   0.0
1742               GB           US         0.0  1785444.0   0.0
1743               GB           US         0.0   185326.0   0.0
1753               GB           US         0.0  2004300.0   0.0
...               ...          ...         ...        ...   ...
320984             GB           US     55479.0  4293824.0   0.0
321030             GB           US     56636.0  4161643.0   0.0
321091             GB           US     58359.0  4516041.0   0.0
321114             GB           US     59123.0  4235134.0   0.0
321172             GB           US     61862.0  4715962.0   0.0

[1531 rows x 5 columns]

In [7]:
# 4. Calculate the totals of the freight, mail, and passengers columns for flights from the United Kingdom to the United States.
column_totals = filtered_df_cutdown[['passengers','freight','mail']].sum()
column_totals

passengers     10685608.0
freight       903296879.0
mail           29838395.0
dtype: float64

In [17]:
# 5. Find the top 5 carriers for median route distance (i.e., for all origin-destination pairs that each carrier has, find the median distance after removing duplicates).
df[['distance','unique_carrier_name','origin','dest']]

        distance   unique_carrier_name origin dest
0         8165.0              Emirates    DXB  IAH
1         6849.0              Emirates    DXB  JFK
2         7247.0              Emirates    DXB  ORD
3         8165.0              Emirates    IAH  DXB
4         6849.0              Emirates    JFK  DXB
...          ...                   ...    ...  ...
321404    1448.0  Alaska Airlines Inc.    ANC  SEA
321405    1448.0  Alaska Airlines Inc.    SEA  ANC
321406    1448.0  Alaska Airlines Inc.    ANC  SEA
321407     404.0  Delta Air Lines Inc.    MCO  ATL
321408    1448.0  Alaska Airlines Inc.    SEA  ANC

[321409 rows x 4 columns]

In [72]:
# 5. Find the top 5 carriers for median route distance (i.e., for all origin-destination pairs that each carrier has, find the median distance after removing duplicates).
subset_cols = ['unique_carrier_name','origin','dest']
df_unique = df.drop_duplicates(subset=subset_cols)

df_unique = df_unique[['unique_carrier_name','distance','origin','dest']]
df_unique

           unique_carrier_name  distance origin dest
0                     Emirates    8165.0    DXB  IAH
1                     Emirates    6849.0    DXB  JFK
2                     Emirates    7247.0    DXB  ORD
3                     Emirates    8165.0    IAH  DXB
4                     Emirates    6849.0    JFK  DXB
...                        ...       ...    ...  ...
320471  Hawaiian Airlines Inc.     102.0    HNL  LIH
320479    Alaska Airlines Inc.     954.0    LAX  SEA
320515  Hawaiian Airlines Inc.     163.0    KOA  HNL
320673  American Airlines Inc.    1121.0    DFW  MIA
320831  American Airlines Inc.    1121.0    MIA  DFW

[65988 rows x 4 columns]

In [ ]:
# 5. Find the top 5 carriers for median route distance (i.e., for all origin-destination pairs that each carrier has, find the median distance after removing duplicates).
grouped_median = df_unique.groupby('unique_carrier_name').median('distance') 
grouped_median = grouped_median.rename(columns={'distance':'median_distance'})
grouped_median.sort_values('median_distance',ascending=False).head()

                                                    median_distance
unique_carrier_name
Singapore Airlines Ltd.                                      8068.0
Cathay Pacific Airways Ltd.                                  8020.0
Longtail Aviation Ltd.                                       7855.5
Qantas Airways Ltd.                                          7853.0
National Aviation Company of India Limited d/b/...           7707.0

In [41]:
singapore_flights = df_unique.query("unique_carrier_name == 'Singapore Airlines Ltd.'")
singapore_flights.sort_values('distance')

        distance      unique_carrier_name origin dest
1338      1567.0  Singapore Airlines Ltd.    LAX  BRL
49411     1947.0  Singapore Airlines Ltd.    LAX  ATL
132252    3856.0  Singapore Airlines Ltd.    FRA  JFK
151535    3856.0  Singapore Airlines Ltd.    JFK  FRA
1328      4426.0  Singapore Airlines Ltd.    ATL  BRU
189716    4714.0  Singapore Airlines Ltd.    IAH  MAN
196271    4714.0  Singapore Airlines Ltd.    MAN  IAH
1331      4959.0  Singapore Airlines Ltd.    DFW  BRU
49409     5081.0  Singapore Airlines Ltd.    HKG  ANC
229347    5451.0  Singapore Airlines Ltd.    NRT  LAX
227060    5451.0  Singapore Airlines Ltd.    LAX  NRT
1339      5639.0  Singapore Airlines Ltd.    LAX  BRU
44911     6005.0  Singapore Airlines Ltd.    SGN  ANC
215827    6927.0  Singapore Airlines Ltd.    HKG  SFO
206523    6927.0  Singapore Airlines Ltd.    SFO  HKG
1335      7260.0  Singapore Airlines Ltd.    HKG  LAX
19782     7260.0  Singapore Airlines Ltd.    LAX  HKG
39356     7600.0  Singapore Airlines Ltd.    ATL  SHJ
1332      8038.0  Singapore Airlines Ltd.    DFW  SHJ
10924     8041.0  Singapore Airlines Ltd.    HKG  CVG
211667    8068.0  Singapore Airlines Ltd.    SEA  SIN
19787     8068.0  Singapore Airlines Ltd.    SIN  SEA
1334      8120.0  Singapore Airlines Ltd.    HKG  DFW
1340      8330.0  Singapore Airlines Ltd.    LAX  SHJ
293939    8440.0  Singapore Airlines Ltd.    SIN  SFO
290863    8440.0  Singapore Airlines Ltd.    SFO  SIN
1337      8698.0  Singapore Airlines Ltd.    LAX  BOM
1343      8758.0  Singapore Airlines Ltd.    SIN  LAX
1341      8758.0  Singapore Airlines Ltd.    LAX  SIN
1330      8781.0  Singapore Airlines Ltd.    DFW  BOM
15616     8983.0  Singapore Airlines Ltd.    ATL  BLR
1336      9000.0  Singapore Airlines Ltd.    LAX  BLR
44900     9133.0  Singapore Airlines Ltd.    BKK  ATL
223131    9485.0  Singapore Airlines Ltd.    EWR  SIN
228165    9485.0  Singapore Airlines Ltd.    SIN  EWR
139292    9487.0  Singapore Airlines Ltd.    SIN  JFK
148035    9487.0  Singapore Airlines Ltd.    JFK  SIN
1342      9642.0  Singapore Airlines Ltd.    SIN  DFW
1333      9642.0  Singapore Airlines Ltd.    DFW  SIN
157656    9838.0  Singapore Airlines Ltd.    IAH  SIN
158096    9838.0  Singapore Airlines Ltd.    SIN  IAH
1329      9866.0  Singapore Airlines Ltd.    ATL  SIN
44903    10314.0  Singapore Airlines Ltd.    DFW  PER

In [91]:
# 6. Find the total cargo transported (mail + freight) and mean distance traveled for the 10 carriers that transported the most cargo.
df_cargo = df[['freight','mail','distance','unique_carrier_name']]
df_cargo

          freight     mail  distance   unique_carrier_name
0         53185.0      0.0    8165.0              Emirates
1          9002.0      0.0    6849.0              Emirates
2       2220750.0      0.0    7247.0              Emirates
3       1201490.0      0.0    8165.0              Emirates
4        248642.0      0.0    6849.0              Emirates
...           ...      ...       ...                   ...
321404   505308.0  15979.0    1448.0  Alaska Airlines Inc.
321405   473666.0  55963.0    1448.0  Alaska Airlines Inc.
321406   592775.0  18834.0    1448.0  Alaska Airlines Inc.
321407   210292.0   5431.0     404.0  Delta Air Lines Inc.
321408   390399.0  44506.0    1448.0  Alaska Airlines Inc.

[321409 rows x 4 columns]

In [93]:
# 6. Find the total cargo transported (mail + freight) and mean distance traveled for the 10 carriers that transported the most cargo.
df_cargo['cargo'] = df_cargo['freight'] + df_cargo['mail']
df_cargo

C:\Users\TylerHa\AppData\Local\Temp\ipykernel_1976\4272874284.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_cargo['cargo'] = df_cargo['freight'] + df_cargo['mail']

          freight     mail  distance   unique_carrier_name      cargo
0         53185.0      0.0    8165.0              Emirates    53185.0
1          9002.0      0.0    6849.0              Emirates     9002.0
2       2220750.0      0.0    7247.0              Emirates  2220750.0
3       1201490.0      0.0    8165.0              Emirates  1201490.0
4        248642.0      0.0    6849.0              Emirates   248642.0
...           ...      ...       ...                   ...        ...
321404   505308.0  15979.0    1448.0  Alaska Airlines Inc.   521287.0
321405   473666.0  55963.0    1448.0  Alaska Airlines Inc.   529629.0
321406   592775.0  18834.0    1448.0  Alaska Airlines Inc.   611609.0
321407   210292.0   5431.0     404.0  Delta Air Lines Inc.   215723.0
321408   390399.0  44506.0    1448.0  Alaska Airlines Inc.   434905.0

[321409 rows x 5 columns]

In [104]:
# 6. Find the total cargo transported (mail + freight) and mean distance traveled for the 10 carriers that transported the most cargo.
grouped_df_cargo = df_cargo.groupby('unique_carrier_name').agg({'cargo': 'sum', 'distance': 'mean'})
grouped_df_cargo = grouped_df_cargo.rename(columns={'cargo': 'total_cargo','distance': 'mean_distance'})
grouped_df_cargo.sort_values('total_cargo',ascending=False).head(10)

                              total_cargo  mean_distance
unique_carrier_name
Federal Express Corporation  1.270966e+10    1121.887981
United Parcel Service        9.173867e+09    1030.812650
Atlas Air Inc.               3.356847e+09    1900.987202
United Air Lines Inc.        1.577892e+09    1810.656058
American Airlines Inc.       1.353074e+09    1583.185048
Kalitta Air LLC              1.272180e+09    2519.580343
Polar Air Cargo Airways      1.199386e+09    3111.794118
Delta Air Lines Inc.         1.129524e+09    1612.688752
China Airlines Ltd.          8.370799e+08    5828.277778
Cathay Pacific Airways Ltd.  7.741777e+08    7498.685315

In [150]:
# 7. Which 10 carriers flew the most passengers out of the United States to another country?
flights_outof_US = df[(df['origin_country']=='US') & (df['dest_country']!='US')]
flights_outof_US = flights_outof_US[['passengers','unique_carrier_name','origin_country','dest_country']]
flights_outof_US

        passengers  unique_carrier_name origin_country dest_country
3              0.0             Emirates             US           AE
4              0.0             Emirates             US           AE
5              0.0             Emirates             US           AE
10             0.0      Kalitta Air LLC             US           CN
13             0.0      Kalitta Air LLC             US           CN
...            ...                  ...            ...          ...
320933     54317.0  British Airways Plc             US           GB
320956     54776.0  British Airways Plc             US           GB
320962     54886.0  British Airways Plc             US           GB
321051     57313.0  British Airways Plc             US           GB
321112     58959.0  British Airways Plc             US           GB

[35026 rows x 4 columns]

In [186]:
# 7. Which 10 carriers flew the most passengers out of the United States to another country?
flights_outof_US_grouped = flights_outof_US.groupby('unique_carrier_name').sum('passengers')
flights_outof_US_grouped = flights_outof_US_grouped.sort_values('passengers',ascending=False).head(10)
flights_outof_US_grouped

                           passengers
unique_carrier_name
American Airlines Inc.     14867653.0
United Air Lines Inc.      14427923.0
Delta Air Lines Inc.       13054230.0
JetBlue Airways             4522492.0
British Airways Plc         3758945.0
Lufthansa German Airlines   3123611.0
Westjet                     2626600.0
Air Canada                  2540855.0
Southwest Airlines Co.      2146960.0
Virgin Atlantic Airways     2074735.0

In [191]:
# 8. For each of the carriers found in #7, find the most popular destination country outside of the United States.
flights_outof_US_with_dest = flights_outof_US.groupby(['unique_carrier_name', 'dest_country']).agg({'dest_country':'count'})
flights_outof_US_with_dest = flights_outof_US_with_dest.rename(columns={'dest_country':'dest_country_count'})
flights_outof_US_with_dest

                                                   dest_country_count
unique_carrier_name                  dest_country
ABC Aerolineas SA de CV dba Interjet ID                             1
                                     MX                           246
ABS JETS A.S                         BM                             1
                                     CA                             4
                                     CZ                             2
...                                                               ...
XL Airways France                    FR                            21
Xiamen Airlines Co., Ltd.            CN                            45
Xtra Airlines  dba  Avelo Airlines   CU                            12
                                     DO                             3
                                     KY                            13

[1457 rows x 1 columns]